### ISSUE TITLE
Define default cursor positions for New Line

### ISSUE THREAD

**Issue by zimlu02** [eclipse-che4z/che-che4z-lsp-for-cobol#1160]
As a developer, I would like to speed up my code writing by having predefined positions for the cursor for a new line.

The suggestion is the following rule:

If your cursor is on column 1-11, the cursor on the new line is placed at column 8.
Else your cursor is placed under the left-most non-blank character between columns 12 and 71 from the previous line or column 12, whichever is greater.

**Comment by markklerks** [comment]
I support this suggestion, because COBOL source code is only to be edited between columns 12 - 71 and not beyond.
