### ISSUE TITLE
Breadcrumbs do not show SECTION for COPY statements

### ISSUE THREAD

**Issue by VitGottwald** [eclipse-che4z/che-che4z-lsp-for-cobol#1172]
## Description ##
Breadcrumbs do not show _section_ when cursor is on COPY statement

## Steps to reproduce ##
1. Open a cobol file
2. Navigate to a COPY statement
3. See that the breadcrumb only shows _DIVISION_ but not _SECTION_

## Expected behavior ##
_SECTION_ where the COPY statement is coded should be included in the breadcrumb

## Screenshots ##

<img width="788" alt="Screenshot 2021-10-29 at 16 41 44" src="https://user-images.githubusercontent.com/19686979/139457030-99d1bd57-d3a4-4c7e-aa77-4072876d3253.png">
<img width="1242" alt="Screenshot 2021-10-29 at 16 41 35" src="https://user-images.githubusercontent.com/19686979/139457058-f6bbcfb7-1812-4215-be69-effc7aef8c38.png">

## Environment ##
VSCode, MacOS

**Comment by slavek-kucera** [comment]
Note: This seems to happen only when the COPY statement is at the end of the section i.e. the section (or division or program) range is not expanded to include the copy statement(s).

**Comment by VitGottwald** [comment]
Cannot reproduce anymore.
