### ISSUE TITLE
EXIT SECTION

### ISSUE THREAD

**Issue by COBOL-Erik** [eclipse-che4z/che-che4z-lsp-for-cobol#1226]
"EXIT SECTION" is a valid COBOL statement, but it is marked as an error:
Extraneous input 'section' expected END-PERFORM COBOL Language Support - E

**Comment by temanbrcom** [comment]
Hi @COBOL-Erik,

Thank you for reporting! Could you, please, provide a code example where it reproduces.

**Comment by COBOL-Erik** [comment]
Hi,
Sure!
This COBOL code compiles on Z, but the COBOL Language Support extension editor complains about "section" in "exit section".

       identification division.
       program-id. DUMMY.
       author. COBOL-Erik.
       environment division.
       data division.
       procedure division.
       A-MAIN         section.
           perform B
           goback
           .

       B              section.
           display 'Hello'
           exit section
           display '(... but no goodbye)'
           .

(The editor also flags "B" in "B section" as a misspelled word.)

**Comment by temanbrcom** [comment]
Thank you! I managed to reproduce the issue, We are working on the fix.
