### ISSUE TITLE
SQL: Support EXEC SQL VAR

### ISSUE THREAD

**Issue by GitMensch** [eclipse-che4z/che-che4z-lsp-for-cobol#1256]
This is a hint to the SQL preparser about the type of bind variables on the DB side, samples:

```cobol
           EXEC SQL VAR MYTYPE        IS CHAR      END-EXEC.
           EXEC SQL VAR MYKEY         IS CHAR      END-EXEC.
```
Those references are bind variables (so part of the sql `DECLARE SECTION`).
It is possibly totally fine to just "skip" those lines in the lsp.

Current result:

```json
{
	"resource": "test.pco",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Syntax error on 'VAR' expected {BEGIN, DECLARE, END, INCLUDE}",
	"source": "COBOL Language Support - E",
	"startLineNumber": 73,
	"startColumn": 21,
	"endLineNumber": 73,
	"endColumn": 24
}
```

**Comment by zimlu02** [comment]
There is an option to turn off CICS or SQL in settings. Would this help? 

    "cobol-lsp.analysis.features": [
        "CICS", "SQL"
    ]

**Comment by VitGottwald** [comment]
Hello @GitMensch `EXEC SQL VAR` looks like a non-standard extension that is not supported by IBM Enterprise COBOL for z/OS.

**Comment by VitGottwald** [comment]
And it's Db2 preprocessor.

**Comment by GitMensch** [comment]
Yes, this is not in the statement list https://www.ibm.com/docs/en/db2/11.5?topic=sql-statements which instead uses [`USAGE SQL TYPE`](https://www.ibm.com/docs/en/db2-for-zos/13?topic=cobol-host-variables-in) after `EXEC SQL BEGIN DECLARE SECTION`. Just to recheck: is that supported completely?

Otherwise it is "only" a common extension for (nearly all?) other SQL preprocessors, so I'd suggest to not close it but move it to an open sql dialect issue instead... or come back to this as part of #2158.

**Comment by VitGottwald** [comment]
All of Db2 SQL including host variables should be supported with the recent [2.2.0](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/releases/tag/2.2.0) release.
