### ISSUE TITLE
upgrade the version of the logback 

### ISSUE THREAD

**Issue by ishche** [eclipse-che4z/che-che4z-lsp-for-cobol#1553]
Let's update the logback to the latest version (it's 1.4.1 now)

**Comment by GitMensch** [comment]
the [Lockback download page](https://logback.qos.ch/download.html) says:

> The current actively developed version of logback supporting Java EE (java.* namespace) is 1.3.14. It requires SLF4J version 2.0.7 and JDK 8.
>
> The current actively developed version of logback supporting Jakarta EE (jakarta.* namespace) is 1.4.14. It requires SLF4J version 2.0.7 and JDK 11.

So is an 1.4.x really reasonable?

**Comment by ishche** [comment]
It's a good point. Let's postpone this issue for a while.
