### ISSUE TITLE
REPLACE issue

### ISSUE THREAD

**Issue by GitMensch** [eclipse-che4z/che-che4z-lsp-for-cobol#1762]
## Description ##
Because `END-DISPLAY` is currently not supported I wanted to `REPLACE` that away, but that obviously doesn't work.

## Steps to reproduce ##
Check with
```cobol
       IDENTIFICATION DIVISION.         
       PROGRAM-ID. HELLO.
       
       REPLACE ==END-DISPLAY== BY ====.

       PROCEDURE DIVISION.
       MAIN-PARAGRAPH.

              display "hello world"
              end-display
              goback.
```
See error about "end-display" which should be removed before /in the initial parsing phase.

## Expected behavior ##
error-free source.

## Screenshots ##
![grafik](https://user-images.githubusercontent.com/6699539/215266839-fb3f28f0-97bb-487f-babc-fea1315dcfde.png)

## Additional information ##
Of course it would be nice to have `END-DISPLAY` (added with COBOL2002) be supported with the upcoming dialect feature...

**Comment by zimlu02** [comment]
Thank you for reporting this.
We will research supporting the REPLACE statement.

**Comment by GitMensch** [comment]
Do you have an "beta" extension version published so people can check the work-in-progress?
Any rough ETAs for 2.0.0?

**Comment by zimlu02** [comment]
Hi Simon,
Yes, all new features marked with the tag 'released on development' should be available on our public [Jenkins](https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/development/) (you can navigate there from this repository, the link can be found in PR checks). 
However from next week on, we plan to move the build process to GitHub Action, so then you would be able to find DEV builds there. Does this work for you?
The ETA for 2.0.0 is end of April.
