### ISSUE TITLE
Validation of Cobol copybook variables in SQL blocks

### ISSUE THREAD

**Issue by Trisk3lion** [eclipse-che4z/che-che4z-lsp-for-cobol#1776]
## Description ##
Cobol host variables which resides in an Copybook are incorrectly are not found by the LSP server when used in an SQL block,  even thou the server has found the copybook itself.

## Steps to reproduce ##
1. Add a copybook to Cobol source file.
"COPY MYCOPY."

MYCOPY:
01 MYCOPY-HS.
     10 COLUMN-ONE PIC X.

2. Reference the copybook variables in an SQL block:
EXEC SQL
SELECT column_one
INTO :mycopy-hs.column-one
FROM my_table
WHERE :mycopy-hs.column-one = '1'
END-EXEC

## Expected behavior ##
That ":mycopy-hs.column-one" is **not** highlighted as "not defined".

## Environment ##
 - OS: Windows 10
 - IDE: VS Code

Or is there something I may have misconfigured?

**Comment by VitGottwald** [comment]
Looks like the problem is in recognizing the syntax `structure.field` inside SQL.

**Comment by Trisk3lion** [comment]
Commmit #2001 fixed this issue!

Thanks for your hard work!
