### ISSUE TITLE
The extension keeps on switching to Output tab when there is some problem.

### ISSUE THREAD

**Issue by plavjanik** [eclipse-che4z/che-che4z-lsp-for-cobol#1827]
## Description ##

The extension has some problems while processing my code and it keeps on displaying an error message and switching to the Output tab from the currently active tab.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/7644758/231567393-99d3ea78-56f9-4ceb-8a5c-1738dde3825a.png">

I am not pressing Go to output but it goes to output automatically.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/7644758/231567494-d378fcae-9c52-41a9-abd1-14efe1ec19fe.png">

## Steps to reproduce ##

I am not doing anything, it just happens even if I am doing unrelated actions.

The workaround is to switch back to the tab that I was using. Or to disable the extension which is unfortunately my choice because the problem is disruptive.

## Expected behavior ##

No change of active UI element. The error should be reported without affecting current workflow if it is not related.

## Environment ##
 - OS: macOS 13.3.1 (22E261)
 - IDE: VS Code 1.77.1
 - COBOL Language Support: v1.2.1

VS Code info:
```
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:22:38.708Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```

## Additional information ##

There is an invalid error displayed in my code:

```cbl
       COPY ZTESTWS1 SUPPRESS REPLACING ==:TAG:== BY ==ZWS==.
```

The code is correct and can be compiled.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/7644758/231567995-1cb9eb66-467b-450a-a68f-561edabf877f.png">

<img width="963" alt="image" src="https://user-images.githubusercontent.com/7644758/231568064-6c86c2d5-1581-4275-9324-a7555deb733e.png">

The contents of the output tab:

```
[Error - 9:41:07 PM] Request textDocument/codeAction failed.
  Message: Message could not be parsed.
  Code: -32700 
[object Object]
[Error - 9:42:28 PM] Request textDocument/codeAction failed.
  Message: Message could not be parsed.
  Code: -32700 
[object Object]
[Error - 9:42:32 PM] Request textDocument/codeAction failed.
  Message: Message could not be parsed.
  Code: -32700 
[object Object]
```

**Comment by zimlu02** [comment]
Hi Petr, 
there are two related issues connected to this ticket:
- #1833 
- #1816

The originally reported issue is now fixed in development, so I am closing this ticket.
