### ISSUE TITLE
Feedback report from ISPF users that attended a Code4z COBOL workshop

### ISSUE THREAD

**Issue by boris-bc** [eclipse-che4z/che-che4z-lsp-for-cobol#1834]
- trimming spaces at EOL
- support for sequence numbers
- support for column 1-6 (?)
- still considering ISPF a better IDE for COBOL

**Comment by zimlu02** [comment]
Thank you for sharing the feedback. Let me put here some notes before closing the ticket.

1. available with right-click option "Format Document"
2. we have Unnumber and Renumber sequence numbers stories in our backlog, however low-priority now
3. not sure what is the request here?
4. what??? :rage2:
