### ISSUE TITLE
Using 'REPOSITORY paragraph' in 'Configuration section' throws syntax error

### ISSUE THREAD

**Issue by fbeyl** [eclipse-che4z/che-che4z-lsp-for-cobol#1835]
## Description ##
'Repository' keyword isn't recognized.
Ex.
```
       cbl dll,thread,dbcs,pgmname(longmixed),list,map
       Identification division.
       Program-id. "SNDKAFKA" is recursive.
       Environment division.
       Configuration section.
       Special-Names.
            Decimal-Point is comma.
       Repository.
           Class ZUtil         is "com.ibm.jzos.ZUtil"
           Class JavaException is "java.lang.Exception"
           Class jdbb          is "java.nio.ByteBuffer"
           Class ToKafka       is "CobolToKafka.ToKafka".
       Input-output section.
       File-control.
           Select Indata assign to INDATA.
       Data Division.
```
throws

Syntax error on 'Repository' expected {CBL, CONFIGURATION, DATA, END, ID, IDENTIFICATION, INPUT-OUTPUT, OBJECT-COMPUTER, PROCEDURE, PROCESS, SOURCE-COMPUTER, SPECIAL-NAMES}COBOL Language Support (parsing)

## Steps to reproduce ##

1. Use Repository keyword
2. Hover over to see error.

## Expected behavior ##
Accept 'Repository' as valid.

## Environment ##

 - OS: Linux Mint 20.3
 - IDE: VS Code
 - Extension: COBOL Language Support v1.2.1

**Comment by zimlu02** [comment]
This is fixed in the latest development build that can be found as an artifact in GitHub Actions [tab](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/actions).
It will be part of the official release of version 2.0.0.
