### ISSUE TITLE
relative file support for "cobol-lsp.cpy-manager.paths-local" does not work

### ISSUE THREAD

**Issue by GitMensch** [eclipse-che4z/che-che4z-lsp-for-cobol#1890]
## Description ##
Tested with both 1.2.1 and 2.0RC: I cannot get local  copybooks to be resolved relative to the current open file.

## Steps to reproduce ##
1. Setup:
   ```json
   "cobol-lsp.cpy-manager.paths-local": ["."]
   ```
2. File "TEST.COB" with `COPY TESTCP.` and a file `TESTCP` directly next to the TEST.COB

## Expected behavior ##
Relative paths from current file works with `"."` - or the description says how to configure that.
In any case I'd assume a _standard_ configuration for `cobol-lsp.cpy-manager.paths-local` that includes copybooks next to the active file (or for nested copybooks: next to a resolved copybook)

**Comment by amanPras** [comment]
The path provided in the **settings is relative to the workspace** and not the currently opened text document._

![image](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/69206564/d5a342e6-f5da-4309-9f5c-37648033c5b8)

Scenario: Workspace contains some folder (cobol in the below screenshot), which holds the copybook and cobol program.
Below are the wrong settings, as the "." in the configuration is seen as the workspace folder. A correct setting in the below case would be "./cobol"

![image](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/69206564/784fbb3e-6c03-49de-8e54-3c9aba01a8fe)

**Comment by GitMensch** [comment]
How do you do that with multi-root workspaces?

And how do you actually resolve a copybook relative to the file doing the `COPY`?

**Comment by amanPras** [comment]
COBOL LS doesn't support multi-root workspace at the moment, however, it is in our backlog.

The second question is a bit unclear, but the main concept is to avoid resolving the copybook relative to the file that is performing the copy operation. Instead, the idea is to provide a path that is relative to the workspace. This approach ensures that the same copybook settings are maintained for COBOL programs located in different folders but utilizing the same copybook.

**Comment by GitMensch** [comment]
To support both you'd allow variables:

$(workspace) -> its root
$(workspace:cpy) -> the root of the mutli-root woprkspace cpy
. -> direct in the folder of the including source

**Comment by zimlu02** [comment]
The relative paths are supported in single workspace scenario and we  will cover it also for multi-workspace scenario within the issue #1257

**Comment by GitMensch** [comment]
Which version (ideally which commit) ships the fix?

**Comment by amanPras** [comment]
> Which version (ideally which commit) ships the fix?

relative path support for a single workspace is present since a long time. You can give a try to 2.0,2. 
By relative path, we mean, relative to the workspace and not relative to the source file. 
AFAIK, we don't plan to support relative to the source file. @zimlu02 Would know more.
 
We still don't support multi-root workspace . 
And so, we don't support the suggested variable [$(workspace)].

For tracking of the multi-root workspace, please refer to https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/issues/1257

**Comment by GitMensch** [comment]
> By relative path, we mean, relative to the workspace and not relative to the source file.
AFAIK, we don't plan to support relative to the source file. @zimlu02 Would know more.

Why? Note that this _explicit_ was the point of this issue

> * Setup:
>   ```json
>   "cobol-lsp.cpy-manager.paths-local": ["."]
>   ```
> 
> * File "TEST.COB" with `COPY TESTCP.` and a file `TESTCP` directly next to the TEST.COB

While `$(workspace)` and `$(workspace)/..` would be the standard way to denote the workspace root / a folder relative to that (which allows `..` to mean "relative to the file") you could of course also define "everything is local, if you want a path relative to the open file then use `${fileDirname}..`" (which would be "kind of standard", too).

**Comment by zimlu02** [comment]
continued in https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/issues/2097
