### ISSUE TITLE
Support for User-defined-functions

### ISSUE THREAD

**Issue by Trisk3lion** [eclipse-che4z/che-che4z-lsp-for-cobol#1926]
**Is your feature request related to a problem?**
Enterprise Cobol 6.4 added support for [User-definied functions](https://www.ibm.com/docs/en/cobol-zos/6.4?topic=applications-using-user-defined-functions), and when used in program it generated errors and seems to stop the parsing from continueing past the function declaration.

**Describe the solution you'd like**
Support for the new keyword "FUNCTION-ID" and support for their being a user-defined functions defined before the main program which are then taken into consideration by the parser in the main program.

**Comment by zimlu02** [comment]
Hello,
we have to split the effort here into two phases. At first, we would only tolerate user-defined-functions. 
The full support would come later (within a new issue).

**Comment by VitGottwald** [comment]
Hello @Trisk3lion, we have looked into this and except for one trivial sample in the [Enterprise COBOL programming guide](https://publibfp.dhe.ibm.com/epubs/pdf/igy6pg40.pdf#page=633) and a few tests in the GNU COBOL compiler ([here](https://svn.code.sf.net/p/gnucobol/code/branches/gnucobol-3.x/tests/testsuite.src/run_functions.at), and [here](https://svn.code.sf.net/p/gnucobol/code/branches/gnucobol-3.x/tests/testsuite.src/syn_functions.at)) there does not seem to be much out there.

Can you provide a real world example that can be shared publicly to help us add this feature and properly test it?

**Comment by Trisk3lion** [comment]
Hello (again) @VitGottwald.

I can't provide a real world example because after filing this issue I discovered that there are issues with using user-defined functions and SQL in the same file/compilation unit; [they now spell it out](https://www.ibm.com/docs/en/cobol-zos/6.4?topic=functions-structuring-user-defined). Which made me go with nested subprograms for the use-case I had at that moment.

But I can provide some simple examples that I have tried and know compiles and works on z/OS 3.1 with Enterprise COBOL 6.4.

1. User-defined functions in the same file as the "main" COBOL program. This is probably not the main way these will be used but in some cases it can probably make code easier to write and read.

```
       identification division.
       function-id. hello.
       environment division.
       data division.
       linkage section.
       01 a-name pic x(20).
       01 greeting pic x(50).
       procedure division using a-name returning greeting.

           initialize greeting
           string 'Hello ' delimited by size
               a-name delimited by space
               into greeting

           goback
           .
       end function hello.

       identification division.
       function-id. myadd.
       environment division.
       data division.
       linkage section.
       01 number1 pic S9(04) COMP-3.
       01 number2 pic S9(04) COMP-3.
       01 summa pic S9(04) COMP-3.
       procedure division using number1 number2 returning summa.

           compute summa = number1 + number2
           goback
           .
       end function myadd.

       identification division.
       program-id funtest.
       environment division.
       configuration section.
       repository. function myadd.
       data division.
       working-storage section.
       01 my-name    pic x(20).
       01 function-return pic x(50).

       01 my-numbers.
           05 value1   pic s9(04) COMP-3.
           05 value2   pic s9(04) COMP-3.
           05 sum-of-values pic 9(05).

       procedure division.

           move 'Kristofer' to my-name
           display 'Calling function "hello"...'
      *> Run user-defined function with the 'function' keyword
           move function hello(my-name) to function-return
           display 'Return value: ' function-return

           move 20 to value1
           move 30 to value2
           display 'Calling function "myadd"...'
      *> Run user-defined function without keyword because of
      *> the 'repository. function myadd.' 
           move myadd(value1 value2) to sum-of-values
           display 'The sum is: ' sum-of-values

           goback
           .
       end program funtest.

```

This program can be compiles under z/OS Unix with; ` cob2 -v -e FUNTEST funtest.cbl -o funtest.out`. Run it with `./funtest.out`.


2. The second way (and probably better) is using [function prototypes](https://www.ibm.com/docs/en/cobol-zos/6.4?topic=applications-using-function-prototypes). Here we have one file with the user-defined functions, one copy with the function prototypes and one "main" program file. Here U use static calling for the function prototypes, but dynamic and DLL are also possible.

Function prototypes, PROTOCOP.cpy:
```
       identification division.
       function-id. hello is prototype entry-interface is static.
       environment division.
       data division.
       linkage section.
       01 a-name pic x(20).
       01 greeting pic x(50).
       procedure division using a-name returning greeting.
       end function hello.

       identification division.
       function-id. myadd is prototype  entry-interface is static.
       environment division.
       data division.
       linkage section.
       01 number1 pic S9(04) COMP-3.
       01 number2 pic S9(04) COMP-3.
       01 summa pic S9(04) COMP-3.
       procedure division using number1 number2 returning summa.
       end function myadd.
```

User-defined functions, funcopy.cbl:
```
       copy protocop
       identification division.
       function-id. hello.
       environment division.
       data division.
       linkage section.
       01 a-name pic x(20).
       01 greeting pic x(50).
       procedure division using a-name returning greeting.

           initialize greeting
           string 'Hello ' delimited by size
               a-name delimited by space
               into greeting

           goback
           .
       end function hello.

       identification division.
       function-id. myadd.
       environment division.
       data division.
       linkage section.
       01 number1 pic S9(04) COMP-3.
       01 number2 pic S9(04) COMP-3.
       01 summa pic S9(04) COMP-3.
       procedure division using number1 number2 returning summa.

           compute summa = number1 + number2
           goback
           .
       end function myadd.
```

And last the "main" COBOL program file, funtest2.cbl:
```
       copy protocop.
       identification division.
       program-id funtest2.
       environment division.
       configuration section.
       repository. function myadd.
       data division.
       working-storage section.
       01 my-name    pic x(20).
       01 function-return pic x(50).

       01 my-numbers.
           05 value1   pic s9(04) COMP-3.
           05 value2   pic s9(04) COMP-3.
           05 sum-of-values pic 9(05).

       procedure division.

           move 'Kristofer' to my-name
           display 'Calling function "hello"...'
      *> Run user-defined function with the 'function' keyword
           move function hello(my-name) to function-return
           display 'Return value: ' function-return

           move 20 to value1
           move 30 to value2
           display 'Calling function "myadd"...'
      *> Run user-defined function without keyword because of
      *> the 'repository. function myadd.'
           move myadd(value1 value2) to sum-of-values
           display 'The sum is: ' sum-of-values

           goback
           .
       end program funtest2 .
```

Place these three files in the same folder under z/OS Unix and run `cob2 -v funtest2.cbl funcopy.cbl -o funtest2.out`, then run the program with `./funtest2.cbl`.

I hope this is some help at least!

Best Regards
