### ISSUE TITLE
CCF & Cobol language support problem

### ISSUE THREAD

**Issue by nemirof** [eclipse-che4z/che-che4z-lsp-for-cobol#1953]
In BBVA we have been trying to use Cobol language support and CCF to see the Control Flow of the program but it doesn't show anything. With older versions at least we could see the flow.

@zimlu02, @VitGottwald  thanks

**Comment by VitGottwald** [comment]
COBOL LS 2.0.0 contains a bug that breaks the integration with CCF. We will be publishing a fix soon. As a temporary workaround, please downgrade to COBOL LS 1.2.1.

For instructions how to install an older version of a VS Code extension please see https://code.visualstudio.com/updates/v1_30#_install-previous-versions.

**Comment by zimlu02** [comment]
Hello, 
this should be resolved with the latest release [https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/releases/tag/2.0.1](url) 
Could please try and let us know?
Thank you
