### ISSUE TITLE
Support for "FUNCTION ALL INTRINSIC"

### ISSUE THREAD

**Issue by Trisk3lion** [eclipse-che4z/che-che4z-lsp-for-cobol#2060]
## Description ##
In the REPOSITORY paragraph, the word "ALL" in "FUNCTION **ALL** INTRINSIC" is flagged as an error.

It would be nice if it didn't flag is as an error and it would also be nice if it also took it into account when parsing the rest of the code so you don't get errors when writing intrinsic functions without the "FUNCTION" keyword before.

## Steps to reproduce ##
Add:
```
       REPOSITORY.
           FUNCTION ALL INTRINSIC.
```
Under the "CONFIGURATION SECTION.

## Expected behavior ##
It should not be flagged as an error and the parser should take it into account and not require the "FUNCTION" keyword before intrinsic functions.

## Screenshots ##
![image](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/9075125/2e8b9bd3-d7f3-45ca-a0cc-a47b969c221c)

![image](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/9075125/224e50f2-d411-47fd-8e0d-64785979086f)

## Environment ##
 - OS: Debian 11 running under WSL2 in Windows 11
 - IDE: VS Code

**Comment by zimlu02** [comment]
The parser is currently being redesigned.
We will reevaluate this issue again after these changes...

**Comment by zimlu02** [comment]
also reported in CCF - https://github.com/BroadcomMFD/cobol-control-flow/issues/57
