### ISSUE TITLE
Support relative paths from the current file

### ISSUE THREAD

**Issue by zimlu02** [eclipse-che4z/che-che4z-lsp-for-cobol#2097]
**Describe the solution you'd like**

Provide support of relative paths from the current file, using ${fileDirname} and /.. ( or something similar from the [VSC options](https://code.visualstudio.com/docs/editor/variables-reference))

**Comment by juleskreutzer** [comment]
Support for relative paths or at least the `${fileDirname}` would help us also!

In our environment, we have the following setup:
- Module name
  - prod env 
  - cert env
  - test env 
    - version 1
    - version 2

Our copybooks are resolved via the configuration below:
`
"some_path\\${fileBasenameNoExtension}\\TEST\\*\\SpecificCopybooks",
"some_path\\${fileBasenameNoExtension}\\PROD\\*\\SpecificCopybooks",
"some_path\\${fileBasenameNoExtension}\\CERT\\*\\SpecificCopybooks",
` 
This means that the incorrect version of a copy book could be used, for example when the user has multiple versions from a specific copybook locally, or if the user is viewing the source/copybook from PROD or CERT, but also has the TEST variant locally.

Support for `${fileDirname}` or relative path means that we can point the LSP to the exact copybook location that should be used, independend of other versions/environment the user has locally.
