### ISSUE TITLE
Intrinsic FUNCTION TRIM with LEADING / TRAILING support missing

### ISSUE THREAD

**Issue by HypnoticYeti** [eclipse-che4z/che-che4z-lsp-for-cobol#2139]
## Description ##
Any code containing intrinsic FUNCTION TRIM, in combination with LEADING / TRAILING parameter, will result in numerous syntax errors and warning. 

## Steps to reproduce ##
Add:
```
       IDENTIFICATION DIVISION.
       PROGRAM-ID.  TRIM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       
       01  TRIM-OUT-VAL                     PIC X(80).
       
       LINKAGE SECTION.
       
       PROCEDURE DIVISION.
       MAIN SECTION.
           MOVE FUNCTION TRIM('TEST123   ', TRAILING)
             TO TRIM-OUT-VAL
           MOVE FUNCTION TRIM('   TEST123', LEADING)
             TO TRIM-OUT-VAL
           GOBACK.
```

## Expected behavior ##
The use of either TRAILING or LEADING parameters in combination with intrinsic FUNCTION TRIM should not lead to errors and warnings.

## Screenshots ##
![screenshot 39](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/assets/48824081/2dd4d735-ed69-4d60-b5ed-7e6d16046e45)

## Environment ##
OS: Windows 10 (21H2)
IDE: VS Code 1.84.2

## Additional information ##
Workaround: finding and replacing all 'LEADING' and 'TRAILING' with '' makes syntax validation work again.

**Comment by GitMensch** [comment]
Wasn't that fixed by [13c0d31](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/commit/13c0d31fea58901590810439d74eae493a26e06b)?
