### ISSUE TITLE
XML Generate statement gives a NPE

### ISSUE THREAD

**Issue by amanPras** [eclipse-che4z/che-che4z-lsp-for-cobol#2294]
## Description ##
XMLParse statement throws a NPE with following stack trace.
`ERROR org.eclipse.lsp.cobol.service.AnalysisService - An exception thrown while applying analysis for untitled:Untitled-3:
java.lang.NullPointerException: null
    at org.eclipse.lsp.cobol.core.visitor.CobolVisitor.visitXmlParseStatement(CobolVisitor.java:279)`

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO-WORLD.
       DATA DIVISION.
       WORKING-STORAGE SECTION.

       77  TestXmlTag      PIC X(20) VALUE "test". 
       77  OutputXml       PIC X(100).

       PROCEDURE DIVISION.
           
           XML GENERATE OutputXml FROM TestXmlTag                                 
           END-XML
           
           DISPLAY "TestXmlTag:          " TestXmlTag
           DISPLAY "OutputXml:           " OutputXml

           STOP RUN.
           
``` 

## Expected behavior ##
No exception for XMLParse statement

**Comment by amanPras** [comment]
https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/1988

**Comment by swathi-bc** [comment]
Done by Aman
