### ISSUE TITLE
hostvariable support for exec sql block

### ISSUE THREAD

**Issue by amanPras** [eclipse-che4z/che-che4z-lsp-for-cobol#2310]
## Description ##
Following program has multiple issue

Issues:

- Hover and go to definition doesn't work for `SET A_B_C  = :QWE.D-E-F`
-  commenting out variable definition for QWE, shows diagnostics at wrong location

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. hostvariales.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SPECIAL-NAMES.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
       DATA DIVISION.
        FILE SECTION.
        WORKING-STORAGE SECTION.
        01 ASD.
           05 O-P-R PIC X.
        01 QWE.
           05 D-E-F PIC X.
        LINKAGE SECTION.
       PROCEDURE DIVISION.
        MAIN-PROCESSING SECTION.
         MAINLINE-PARAGRAPH.
       EXEC SQL
        UPDATE QWE_STATUS
            SET A_B_C  = :QWE.D-E-F
            WHERE TKN_UNIQUE_REFERENCE = :ASD.O-P-R
       END-EXEC  
           STOP RUN.
``` 
 

## Expected behavior ##

-  Hover and go to definition should work for host variables used in exec blocks
-  Diagnostics should be located at the error source 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by VitGottwald** [comment]
Do we have a PR fixing this @ap891843 ?

**Comment by amanPras** [comment]
> Do we have a PR fixing this @ap891843 ?

We haven't started working on it yet
