### ISSUE TITLE
Support all SQL Host Variables

### ISSUE THREAD

**Issue by VitGottwald** [eclipse-che4z/che-che4z-lsp-for-cobol#2320]
See [_Declaring host variables and indicator variables in COBOL_](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-declaring-host-variables-indicator-variables-in-cobol). The complete PDF can be found [here](https://www.ibm.com/docs/en/SSEPEK_13.0.0/pdf/db2z_13_apsgbook.pdf).

- [x] Numeric host variables
- [x] Character host variables
- [x] Graphic character host variables
- [x] Binary host variables
- [x] LOB variables and file reference variables
- [x] XML data host and file reference variables
- [x] ROWID host variables
- [x] Result set variables
- [x] Table locator variables
- [x] LOB locator variables
- [x] LOB file reference variables
- [x] #2390
- [x] Host-variable arrays in COBOL
  - [x] Numeric host-variable arrays
  - [x] Character host-variable arrays
  - [x] LOB, locator, and file reference variable arrays
  - [x] XML host and file reference variable arrays
  - [x] ROWID variable arrays
- [x] Host structures
  - [x] Numeric usage items
  - [x] Integer and decimal usage items
  - [x] CHAR inner variables
  - [x] VARCHAR inner variables
  - [x] VARGRAPHIC inner variables
  - [x] LOB variables, locators, and file reference variables
  - [x] LOB variables and file reference variables for XML data
- [x] Indicator variables, indicator arrays, and host structure indicator arrays
- [ ] Controlling the CCSID for COBOL host variables

**Comment by amanPras** [comment]
#2365

**Comment by amanPras** [comment]
#2380 #2364

**Comment by VitGottwald** [comment]
Released as part of https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/releases/tag/2.2.0
