### ISSUE TITLE
Support for JCL

### ISSUE THREAD

**Issue by rupurt** [eclipse-che4z/che-che4z-lsp-for-cobol#2438]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
I'd like to use the tooling for JCL. It would also be awesome to do the same thing for BMS, REXX, HLASM etc... :)

**Describe alternatives you've considered**
Using another tool

**Comment by VitGottwald** [comment]
Hello @rupurt, this extension is for COBOL. For HLASM and BMS, there is [HLASM Language Support](https://github.com/eclipse-che4z/che-che4z-lsp-for-hlasm) which is also open source.

For JCL, there is [JCL Language Support](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.jcl-language-support) and for REXX there is [Rexx Language Support](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.lsp-for-rexx). These are available for free but are not open yet. However you can still provide feedback and request features in their associated github repositories. And in case you would like to contribute, let us know. We are always looking for contributors and having such interest would help in conversations about opening those extensions in the future.
