### ISSUE TITLE
Analyzing progress message shows URL encoded characters in its path

### ISSUE THREAD

**Issue by VitGottwald** [eclipse-che4z/che-che4z-lsp-for-cobol#2441]
Instead I would expect to see the unencoded string - in this particular case the parentheses.

![analysing message](https://github.com/user-attachments/assets/4117dd90-f321-474a-b820-5fabcfe1de58)

**Comment by VitGottwald** [comment]
Related to an issue with UNC path handling in Java.

**Comment by amanPras** [comment]
Its not properly handled yet. But with ZOWE V3, we would not face this issue.
