### ISSUE TITLE
Format timings to make them more legible

### ISSUE THREAD

**Issue by VitGottwald** [eclipse-che4z/che-che4z-lsp-for-cobol#2442]
When reading log messages with timings about processing time it is hard to see the order of magnitude.

```
08:35:02.777 [Analysis thread #0] DEBUG org.eclipse.lsp.cobol.common.benchmark.BenchmarkServiceImpl - Timing for Parsing stage: 11859753458
```

Round the precession to microseconds and add thousands separators like `11859753458` -> `11,859,753`

**Comment by ishche** [comment]
fix by https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/2526
