### ISSUE TITLE
Testing the new Endevor Copybook Download feature

### ISSUE THREAD

**Issue by Morridt** [eclipse-che4z/che-che4z-lsp-for-cobol#2447]
## Description ##

Have set up options to enable Endevor download of copybooks, but when editing a COBOL program in Endevor the following messages are displayed:

```
c:\Users\morrid11\AppData\Roaming\Code\User\globalStorage\broadcommfd.explorer-for-endevor\.edit\Endevor\synchronized\W111_1_PAYMENTS_CM\synchronized\PAYMENTS\CM\COBOL\CM004.original'.
2024-08-26T01:25:20.884Z - Setup Endevor session: https:/sybrcd1.sys.au.eds.com:8040/EndevorService/api/v2, rejectUnauthorized: false, type: basic
2024-08-26T01:25:22.651Z - [Telemetry event] edit element command completed: {"type":"edit element command completed","status":"SUCCESS"}
2024-08-26T01:25:24.358Z - Unable to retrieve Endevor Configurations.
2024-08-26T01:25:24.358Z - Unable to retrieve Endevor Configurations because of error: failed to load inventory: fetch failed: Error: unable to verify the first certificate.
```

## Steps to reproduce ##

***VSCode User Settings***

```
    "cobol-lsp.cpy-manager.copybook-extensions": [
        ".COBCOPY",
        ".CPY",
        ".COPY",
        ".cpy",
        ".copy",
        ""
    ],
    "cobol-lsp.cpy-manager.paths-local": [
        "**/COBCOPY"
    ],
    "cobol-lsp.cpy-manager.endevor-dependencies": "ENDEVOR_PROCESSOR",
    "endevor.authWithToken": false,
```

***zowe config list***

```
zowe config list
profiles: 
  W111_1_PAYMENTS_CM: 
    type:       endevor-location
    properties: 
      instance:    ENDEVOR      
      environment: W111
      system:      PAYMENTS
      subsystem:   CM
      type:        *
      stageNumber: 1
      ccid:        CM-09259
      comment:     TESTING 
      maxrc:       8
    secure: 
      (empty array)
  D01_zosmf: 
    type:       zosmf
    properties: 
      port: 443
    secure: 
      (empty array)
  Endevor: 
    type:       endevor
    properties: 
      port:     8040
      basePath: EndevorService/api/v2
    secure: 
      (empty array)
  D01: 
    type:       base
    properties: 
      host:               <host>
      protocol:           https
      rejectUnauthorized: false
      user:               (secure value)
      password:           (secure value)
    secure: 
      - user
      - password
defaults: 
  endevor-location: W111_1_PAYMENTS_CM
  endevor:          Endevor
  base:             D01
  zosmf:            D01_zosmf
autoStore: true
```

## Screenshots ##

![image](https://github.com/user-attachments/assets/5dc139a3-b4dd-49e6-a490-5e2d66e85048)

## Environment ##

- Windows 10
- VSCode 1.92.2
- VSCode - COBOL Language Support v2.2.0
- VSCode - Explorer for Endevor v1.8.1
- VSCode - Zowe Explorer v2.17.0
- Zowe CLI 7.29
- Zowe Endevor -- version: 7.7.6

**Comment by KutluOzel-b** [comment]
@Morridt Are you able to use Explorer for Endevor extension with edit feature without any errors ? This seems a certificate issue on electron that might needs to be investigated with Explorer for Endevor extension due to that you have already bypassed unauthorized requests.

**Comment by Morridt** [comment]
@KutluOzel-b 
Yes we have been using Explorer for Endevor without issue to do edit etc.  

Using zowe cli with Endevor plugins; We've recently set up Bridge4Git with mainframe webhook server running EWS Tomcat.

Certs involved should be fine and managed.

**Comment by VitGottwald** [comment]
@Morridt, please, open a case with Broadcom support against product: `Endevor`, component code: `EXPEND` (Code4z Explorer for Endevor).

I would suspect that you do not have access to the processor element that is used by the generate processor associated with the element you are looking at. Endevor support will be able to clarify that with you.

**Comment by uzuko001** [comment]
Hello @Morridt.
Thanks for creating this issue.
After some investigation we figured that the `rejectUnauthorized` value set in the profile is not properly used in the request to retrieve Endevor configurations.
 It will be fixed in our upcoming Explorer for Endevor 1.8.2 release, which should be available soon.

**Comment by Morridt** [comment]
Thanks.....
I'll update the support case with same : 35733034

**Comment by roman-kupriyanov** [comment]
Hi @Morridt,

We released Explorer for Endevor 1.8.2 and it is available in VSCode Marketplace to update to. Please retest the functionality with the latest version and let us know if the same issue remains or any other issues appeared.

Thank you!

**Comment by Morridt** [comment]
Thanks @roman-kupriyanov .....love your work....

Definitely an improvement and shows users do need read access to the processors.
Have advised our Endevor guys and we'll follow up further in the support case at Broadcom.

`2024-09-17T21:29:12.605Z - Setup Endevor session: https:/sybrcd1.sys.au.eds.com:8040/EndevorService/api/v2, rejectUnauthorized: false, type: basic
2024-09-17T21:29:26.942Z - Unable to retrieve Endevor Configurations.
2024-09-17T21:29:26.942Z - Unable to retrieve Endevor Configurations because of error: failed to load inventory: update processor groups and processors for element CM004/COBOL from W111/1/PAYMENTS/CM: retrieve processor ADMIN_GCBIN01: rc: 0012, rsn: 0000, message: EWS1117I Request processed by SysID D01CCI, STC WSEWSSTC - JOB20602
07:29:26  API0079E  ERRORS WERE DETECTED. REVIEW THE C1MSGS1 EXECUTION REPORT FOR DETAILS
07:29:26  API0000E  ERROR(S) DETECTED, PROCESSING TERMINATED
C1E0106E  ENV SCMS NOT DEFINED IN CUSTOMER DEFAULTS TABLE OR THE USER IS NOT AUTHORIZED TO USE THIS ENV..
2024-09-17T21:29:29.153Z - Unable to retrieve Endevor Configurations.
2024-09-17T21:29:29.153Z - Unable to retrieve Endevor Configurations because of error: failed to load inventory: update processor groups and processors for element CM004/COBOL from W111/1/PAYMENTS/CM: retrieve processor ADMIN_GCBIN01: rc: 0012, rsn: 0000, message: EWS1117I Request processed by SysID D01CCI, STC WSEWSSTC - JOB20603
07:29:28  API0079E  ERRORS WERE DETECTED. REVIEW THE C1MSGS1 EXECUTION REPORT FOR DETAILS
07:29:28  API0000E  ERROR(S) DETECTED, PROCESSING TERMINATED
C1E0106E  ENV SCMS NOT DEFINED IN CUSTOMER DEFAULTS TABLE OR THE USER IS NOT AUTHORIZED TO USE THIS ENV..
2024-09-17T21:29:33.759Z - Unable to retrieve Endevor Configurations.
2024-09-17T21:29:33.759Z - Unable to retrieve Endevor Configurations because of error: failed to load inventory: update processor groups and processors for element CM004/COBOL from W111/1/PAYMENTS/CM: retrieve processor ADMIN_GCBIN01: rc: 0012, rsn: 0000, message: EWS1117I Request processed by SysID D01CCI, STC WSEWSSTC - JOB20604
07:29:33  API0079E  ERRORS WERE DETECTED. REVIEW THE C1MSGS1 EXECUTION REPORT FOR DETAILS
07:29:33  API0000E  ERROR(S) DETECTED, PROCESSING TERMINATED
C1E0106E  ENV SCMS NOT DEFINED IN CUSTOMER DEFAULTS TABLE OR THE USER IS NOT AUTHORIZED TO USE THIS ENV..
`

**Comment by KutluOzel-b** [comment]
Closing the issue due to it is being tracked with Broadcom support
