### ISSUE TITLE
Error when BYTE-LENGTH is used in a PICTURE declaration.

### ISSUE THREAD

**Issue by Trisk3lion** [eclipse-che4z/che-che4z-lsp-for-cobol#2558]
## Description ##
An error is reported when `BYTE-LENGTH` is used in a PICTURE declaration.
Like this:
```
01 JSON-DATA-UTF8 PIC U BYTE-LENGTH 500.
```

The following error is reported:
"A period was assumed before "BYTE-LENGHT"

## Steps to reproduce ##
1. Declare a variable as PIC U BYTE-LENGTH 500
2. Start LSP
4. See error.

## Expected behavior ##
No error reported

## Screenshots ##
![image](https://github.com/user-attachments/assets/b1d06e50-a67a-4a21-9b4d-177a2b61df1b)

## Environment ##
 - OS: WSL2 running under Windows 11
 - IDE: VS Code, Emacs

**Comment by amanPras** [comment]
@Trisk3lion Can you please try the latest dev build ? 
NOTE: validation for no dynamic clause along with UTF byte-length clause have not been added and would be done in future.

**Comment by Trisk3lion** [comment]
> @Trisk3lion Can you please try the latest dev build ? NOTE: validation for no dynamic clause along with UTF byte-length clause have not been added and would be done in future.

I don't get any errors this with the dev build! Good work, thanks!
