### ISSUE TITLE
Error when using DB2 query "SELECT .... INTO .... FROM FINAL TABLE ....."

### ISSUE THREAD

**Issue by Trisk3lion** [eclipse-che4z/che-che4z-lsp-for-cobol#2570]
## Description ##
An error is reported when using the DB2 Syntax `FROM FINAL TABLE`.
https://www.ibm.com/docs/en/db2-for-zos/12?topic=clause-table-reference

For example; with this query:
``` cobol
EXEC SQL
SELECT NAME
INTO :NAME
FROM FINAL TABLE
           (UPDATE MYTABLE
            SET NAME = 'JAMES'
            WHERE ID = :ID)
END-EXEC
```

I get the following error:
"No viable alternative at input FINAL TABLE (UPDATE MYTABLE SET NAME = 'JAMES' WHERE ID = :ID)"

I haven't tested it but probably there is the same issue for "FROM OLD TABLE"

## Steps to reproduce ##
1. Insert the above SQL query in a cobol file
2. Start LSP
3. See error.

## Expected behavior ##
No error reported

## Screenshots ##
<img width="233" alt="image" src="https://github.com/user-attachments/assets/b7ff45fb-f61d-4509-9460-9904cd1c82ce">

## Environment ##
 - OS: WSL2 under Windows 11
 - IDE: VSCode, Emacs

**Comment by ishche** [comment]
So far I see an issue with UPDATE part of the statement. This snipped is accepted by compiler, but cause an issue with our analyser:
```
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TEST1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
           EXEC SQL INCLUDE SQLCA END-EXEC.
       PROCEDURE DIVISION.
           EXEC SQL
           UPDATE DSN8C10.EMP
               SET SALARY = SALARY + 100.
               WHERE WORKDEPT = 'D11'
           END-EXEC.
```
