### ISSUE TITLE
Copybooks with Errors Continue Showing the Diagnostics After Removing the Statements

### ISSUE THREAD

**Issue by temanbrcom** [eclipse-che4z/che-che4z-lsp-for-cobol#491]
## Description ##

If a copybook contains syntax or semantic errors, it will be shown in the project structure as containing diagnostics, as well as the document it was used in. If the user removes the copy statement, the diagnostic from the document disappears, but the copybook remains erroring. 

## Steps to reproduce ##
1. Open a COBOL file that contains some error
1. Make copybook produce a syntax error, e.g. if it contains data definition, move the copy statement to `PROCEDURE DIVISION`
1. Notice a syntax error in the copybook
1. Remove the copy statement 
1. Notice the syntax error in the document disappears, but the copybook remains to show the error

## Expected behavior ##

The state of the copybook clears, no syntax error shown

## Environment ##
 - OS: All
 - IDE: All

## Additional information ##

After #351

**Comment by andreytemn** [comment]
Any updates on this one?
