### ISSUE TITLE
Support Structure Call to Paragraphs and Sections

### ISSUE THREAD

**Issue by temanbrcom** [eclipse-che4z/che-che4z-lsp-for-cobol#612]
**Is your feature request related to a problem?**

Sections in `PROCEDURE DIVISION` may contain nested paragraphs. It allows making calls like `GO TO PAR_NAME IN SEC-NAME.` These calls should be checked for structure correctness. 

**Describe the solution you'd like**

Check that the referencing is correct on structured paragraphs calls. The paragraph names should be unique on usage, i.e. they may duplicate in the section or in the program if there are no references on them.

**Additional information**

It will require changing the structure of the semantic context.

**Comment by Nurkambay** [comment]
It has already been implemented, please take a look at the newest COBOL LS versions
