### ISSUE TITLE
Support Object-oriented Programming with COBOL

### ISSUE THREAD

**Issue by temanbrcom** [eclipse-che4z/che-che4z-lsp-for-cobol#624]
**Is your feature request related to a problem?**

COBOL may support object-oriented programming. It would be nice if COBOL LS may help with it. 

**Describe the solution you'd like**

Syntax and semantic for object-oriented code in COBOL, like `Class` declarations, etc.

**Comment by temanbrcom** [comment]
The decision is that feature has low priority and won't be implemented at the nearest time. If you require this feature, please, contact us to discuss it.

**Comment by VitGottwald** [comment]
Not planned.
