### ISSUE TITLE
Enable double-star in settings for local copybooks path

### ISSUE THREAD

**Issue by dankox** [eclipse-che4z/che-che4z-lsp-for-cobol#698]
**Is your feature request related to a problem?**
To be honest, I'm not sure if this is not an actual bug, but in the `settings.json` when I'm trying to setup local path to copybooks, I have to define full path (from the root of the project).    
This wasn't obvious at first, because I was using vscode default way of specifying path like in `file.associations` and other path specification with double-star `**`.

Example:
```json
    "broadcom-cobol-lsp.cpy-manager.paths-local": [
        "MYAPP/COPY",        // this does work
        "**/COPY",           // this does NOT work
        "**/COPY/*",         // this does NOT work
        "MYAPP/COPY/*.CPY",  // this does NOT work
    ],
```

**Describe the solution you'd like**
It would be good, if all of those options work. Basically implementing `glob` like file search using the paths specified in `settings.json`.    
If not possible for any kind of reason, I think it would be good to have at least the second option to specify path to directory with double-star.

**Describe alternatives you've considered**
I wouldn't call it alternative, but the only other way around it is to document it, so it's obvious how it should be defined.

**Comment by zimlu02** [comment]
Thank you for your suggestion.
We are planning improvements for copybooks path specification for the future. For now, we will definitely review the documentation to be more specific there.

**Comment by zimlu02** [comment]
All now supported.
We can achieve "MYAPP/COPY/*.CPY" this copybook path setting using "copybook-extensions" configuration.
