### ISSUE TITLE
Bad coloring

### ISSUE THREAD

**Issue by grianbrcom** [eclipse-che4z/che-che4z-lsp-for-cobol#815]
1. IMO `C` should not be colored.
![1](https://user-images.githubusercontent.com/65608274/110838270-8dc8ec00-82a2-11eb-958e-f042a6501c22.png)

2.  Is this expected coloring for `LABEL RECORDS ARE STANDART`?
![2](https://user-images.githubusercontent.com/65608274/110838216-7ab61c00-82a2-11eb-95a1-e48b83e5d7e9.png)

3. `HEADER` should be colored? 
![3](https://user-images.githubusercontent.com/65608274/110838376-ab965100-82a2-11eb-93f0-7579ef725bb7.png)
 
4. `filler` should be colored? 
![4](https://user-images.githubusercontent.com/65608274/110838477-c799f280-82a2-11eb-8a7b-33effb9df002.png)

Otherwise, all `DIVISION` statements are colored.

_Originally posted by @nalmabrcom in https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/812#issuecomment-796962103_

**Comment by grianbrcom** [comment]
Numbers 1 and 3 must be fixed. 2 and 4 not an issue, at least from my point of view.

**Comment by temanbrcom** [comment]
As for me, `LABEL RECORDS ARE STANDARD` doesn't contain user-defined identifiers, so it should be blue

**Comment by zimlu02** [comment]
number 1 is fixed
number 3 still present in v1.1.0
